# Use an official SQLite image as a base image
FROM sqlite:latest

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy your SQLite database file into the container
COPY src/server/db.sqlite3 .

# Expose the port SQLite will run on (default is 5432)
EXPOSE 5432

# Command to run the SQLite server
CMD ["sqlite3", "db.sqlite3"]
