# Generated by Django 4.2.7 on 2023-11-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_user_managers_user_date_joined_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_{id}', max_length=100, unique=True),
        ),
    ]
